name: Kimon Krenz, Spatial Data Scientist
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
scholar:
  style: APA
  locale: en
  source: /_bibliography/
  bibliography: references.bib
  sort_by: year,month
  order: descending
